# Generated by Django 5.1.6 on 2025-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('link', models.URLField()),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='project_images/logos/')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='project', to='portfolio.language'),
        ),
    ]
