# Generated by Django 5.1.6 on 2025-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_language_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
