# Generated by Django 5.2 on 2025-04-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_language_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
